
import type { Category, Product, Review } from './types';

export const categories: Category[] = [
  { id: '1', name: "Men's Clothing", slug: 'mens-clothing', imageId: 'cat-mens' },
  { id: '2', name: "Women's Clothing", slug: 'womens-clothing', imageId: 'cat-womens' },
  { id: '3', name: 'Accessories', slug: 'accessories', imageId: 'cat-accessories' },
  { id: '4', name: 'Winter Collection', slug: 'winter-collection', imageId: 'cat-winter' },
];

export const products: Product[] = [
  // Men's Clothing
  {
    id: '27',
    name: 'Long Wool Coat – Hugo Boss',
    slug: 'long-wool-coat-hugo-boss-men',
    description: 'A premium long wool coat offering excellent warmth, sharp tailoring, and timeless winter elegance.',
    price: 620,
    categoryId: '1',
    imageId: 'prod-27',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 15,
    popularity: 92,
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: '28',
    name: 'Quilted Down Jacket – Moncler',
    slug: 'quilted-down-jacket-moncler-men',
    description: 'A lightweight quilted down jacket providing exceptional insulation and signature Moncler sophistication.',
    price: 740,
    categoryId: '1',
    imageId: 'prod-28',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 98,
    createdAt: '2023-11-05T10:00:00Z',
  },
  {
    id: '29',
    name: 'Arctic Parka – Canada Goose',
    slug: 'arctic-parka-canada-goose-men',
    description: 'A high-performance parka engineered for extreme winter temperatures with rugged durability.',
    price: 980,
    categoryId: '1',
    imageId: 'prod-29',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 5.0,
    reviewCount: 42,
    popularity: 99,
    createdAt: '2023-10-28T10:00:00Z',
  },
  {
    id: '30',
    name: 'Cashmere Coat – Loro Piana (Men)',
    slug: 'cashmere-coat-loro-piana-men',
    description: 'A luxurious men\'s cashmere coat known for its unmatched softness, comfort, and Italian craftsmanship.',
    price: 1250,
    categoryId: '1',
    imageId: 'prod-30',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L'],
    rating: 5.0,
    reviewCount: 18,
    popularity: 95,
    createdAt: '2023-11-10T10:00:00Z',
  },
  {
    id: '31',
    name: 'Shearling Jacket – Saint Laurent',
    slug: 'shearling-jacket-saint-laurent-men',
    description: 'A stylish shearling jacket blending modern Saint Laurent attitude with superior winter warmth.',
    price: 1150,
    categoryId: '1',
    imageId: 'prod-31',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 93,
    createdAt: '2023-11-12T10:00:00Z',
  },
  {
    id: '32',
    name: 'Merino Wool Turtleneck – Paul Smith',
    slug: 'merino-wool-turtleneck-paul-smith-men',
    description: 'A soft and breathable merino turtleneck perfect for layering during cold seasons.',
    price: 180,
    categoryId: '1',
    imageId: 'prod-32',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 35,
    popularity: 88,
    createdAt: '2023-10-15T10:00:00Z',
  },
  {
    id: '33',
    name: 'Lined Overshirt – Acne Studios (Men)',
    slug: 'lined-overshirt-acne-studios-men',
    description: 'A warm lined overshirt combining Scandinavian minimalism with practical winter insulation.',
    price: 260,
    categoryId: '1',
    imageId: 'prod-33',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 28,
    popularity: 85,
    createdAt: '2023-10-20T10:00:00Z',
  },
  {
    id: '34',
    name: 'Sleeveless Down Vest – Polo Ralph Lauren',
    slug: 'sleeveless-down-vest-polo-ralph-lauren',
    description: 'A lightweight sleeveless down vest ideal for everyday winter layering.',
    price: 210,
    categoryId: '1',
    imageId: 'prod-34',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 40,
    popularity: 90,
    createdAt: '2023-09-25T10:00:00Z',
  },
  {
    id: '35',
    name: 'Double-Breasted Trench Coat – Burberry',
    slug: 'double-breasted-trench-coat-burberry-men',
    description: 'An iconic Burberry trench redesigned with winter lining and a refined double-breasted silhouette.',
    price: 890,
    categoryId: '1',
    imageId: 'prod-35',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 55,
    popularity: 96,
    createdAt: '2023-09-10T10:00:00Z',
  },
  {
    id: '36',
    name: 'Thick Cable-Knit Sweater – Dior Homme',
    slug: 'thick-cable-knit-sweater-dior-homme',
    description: 'A luxurious cable-knit sweater offering premium warmth and elegant texture.',
    price: 390,
    categoryId: '1',
    imageId: 'prod-36',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 30,
    popularity: 91,
    createdAt: '2023-10-18T10:00:00Z',
  },
  {
    id: '37',
    name: 'Technical Waterproof Jacket – TNF Black Series',
    slug: 'technical-waterproof-jacket-tnf-black-series-men',
    description: 'A weather-resistant technical jacket designed for urban performance and winter protection.',
    price: 320,
    categoryId: '1',
    imageId: 'prod-37',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 45,
    popularity: 89,
    createdAt: '2023-11-15T10:00:00Z',
  },
  {
    id: '38',
    name: 'Thermal Pants – Nike ACG',
    slug: 'thermal-pants-nike-acg',
    description: 'Flexible thermal pants designed for outdoor winter activities and maximum mobility.',
    price: 170,
    categoryId: '1',
    imageId: 'prod-38',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 30,
    popularity: 82,
    createdAt: '2023-11-18T10:00:00Z',
  },
  {
    id: '39',
    name: 'Double Wool Peacoat – Sandro',
    slug: 'double-wool-peacoat-sandro',
    description: 'A modern double-breasted peacoat crafted in warm wool for a timeless winter look.',
    price: 350,
    categoryId: '1',
    imageId: 'prod-39',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 25,
    popularity: 88,
    createdAt: '2023-11-20T10:00:00Z',
  },
  {
    id: '40',
    name: 'Premium Down Jacket – Armani Exchange',
    slug: 'premium-down-jacket-armani-exchange',
    description: 'A stylish padded jacket combining Armani design codes with effective insulation.',
    price: 430,
    categoryId: '1',
    imageId: 'prod-40',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 22,
    popularity: 86,
    createdAt: '2023-11-22T10:00:00Z',
  },
  {
    id: '41',
    name: 'Velvet Coat – Zegna',
    slug: 'velvet-coat-zegna',
    description: 'A luxurious velvet coat with a refined structure and impeccable Italian finishing.',
    price: 1050,
    categoryId: '1',
    imageId: 'prod-41',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 5.0,
    reviewCount: 15,
    popularity: 94,
    createdAt: '2023-11-25T10:00:00Z',
  },
  {
    id: '42',
    name: 'Long Belted Wool Coat – Max Mara (Men)',
    slug: 'long-belted-wool-coat-max-mara',
    description: 'A tailored belted coat made from premium wool for warmth and sophistication.',
    price: 780,
    categoryId: '1',
    imageId: 'prod-42',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 20,
    popularity: 91,
    createdAt: '2023-11-28T10:00:00Z',
  },
  {
    id: '43',
    name: 'Synthetic Fur Parka – Canada Goose',
    slug: 'synthetic-fur-parka-canada-goose',
    description: 'A winter parka trimmed with eco-friendly synthetic fur for superior protection.',
    price: 880,
    categoryId: '1',
    imageId: 'prod-43',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 35,
    popularity: 90,
    createdAt: '2023-12-01T10:00:00Z',
  },
  {
    id: '44',
    name: 'Shearling Jacket – Acne Studios (Unisex)',
    slug: 'shearling-jacket-acne-studios-unisex',
    description: 'A minimalist shearling jacket offering modern style and outstanding warmth.',
    price: 920,
    categoryId: '1',
    imageId: 'prod-44',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 28,
    popularity: 92,
    createdAt: '2023-12-03T10:00:00Z',
  },
  {
    id: '45',
    name: 'Oversized Wool Sweater – Jacquemus',
    slug: 'oversized-wool-sweater-jacquemus',
    description: 'A cozy oversized wool sweater with a fashion-forward Jacquemus silhouette.',
    price: 260,
    categoryId: '1',
    imageId: 'prod-45',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 18,
    popularity: 87,
    createdAt: '2023-12-05T10:00:00Z',
  },
  {
    id: '46',
    name: 'XXL Puffer Coat – Zara Premium',
    slug: 'xxl-puffer-coat-zara-premium',
    description: 'A warm and comfortable oversized puffer coat designed for bold winter looks.',
    price: 160,
    categoryId: '1',
    imageId: 'prod-46',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 40,
    popularity: 85,
    createdAt: '2023-12-08T10:00:00Z',
  },
  // Women's Clothing
  {
    id: '47',
    name: 'Silk Midi Dress – Gucci',
    slug: 'silk-midi-dress-gucci',
    description: 'A luxurious silk midi dress offering fluid movement and refined winter elegance.',
    price: 950,
    categoryId: '2',
    imageId: 'prod-47',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 28,
    popularity: 94,
    createdAt: '2023-11-08T10:00:00Z',
  },
  {
    id: '48',
    name: 'Double-Breasted Blazer – Balmain',
    slug: 'double-breasted-blazer-balmain',
    description: 'A structured double-breasted blazer showcasing iconic Balmain tailoring.',
    price: 780,
    categoryId: '2',
    imageId: 'prod-48',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 35,
    popularity: 97,
    createdAt: '2023-11-02T10:00:00Z',
  },
  {
    id: '49',
    name: 'Cashmere Turtleneck – Loro Piana (Women)',
    slug: 'cashmere-turtleneck-loro-piana-women',
    description: 'A premium cashmere turtleneck designed for exceptional softness and warmth.',
    price: 420,
    categoryId: '2',
    imageId: 'prod-49',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 20,
    popularity: 96,
    createdAt: '2023-10-25T10:00:00Z',
  },
  {
    id: '50',
    name: 'Wide-Leg Wool Pants – Max Mara',
    slug: 'wide-leg-wool-pants-max-mara',
    description: 'Elegant wool trousers with a warm, flowing silhouette suited for winter outfits.',
    price: 320,
    categoryId: '2',
    imageId: 'prod-50',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 15,
    popularity: 88,
    createdAt: '2023-10-10T10:00:00Z',
  },
  {
    id: '51',
    name: 'Premium Slim Jeans – Diesel',
    slug: 'premium-slim-jeans-diesel',
    description: 'High-quality slim jeans designed for comfort and durability in cooler weather.',
    price: 180,
    categoryId: '2',
    imageId: 'prod-51',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['26', '27', '28', '29', '30'],
    rating: 4.6,
    reviewCount: 50,
    popularity: 85,
    createdAt: '2023-09-20T10:00:00Z',
  },
  {
    id: '52',
    name: 'Printed Silk Blouse – Saint Laurent',
    slug: 'printed-silk-blouse-saint-laurent',
    description: 'An elegant printed silk blouse with sophisticated Saint Laurent detailing.',
    price: 440,
    categoryId: '2',
    imageId: 'prod-52',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 91,
    createdAt: '2023-11-18T10:00:00Z',
  },
  {
    id: '53',
    name: 'Wool Short Dress – Prada',
    slug: 'wool-short-dress-prada',
    description: 'A warm and modern wool dress perfect for chic cold-season outfits.',
    price: 850,
    categoryId: '2',
    imageId: 'prod-53',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.8,
    reviewCount: 18,
    popularity: 89,
    createdAt: '2023-11-20T10:00:00Z',
  },
  {
    id: '54',
    name: 'Long Cashmere Coat – Max Mara (Women)',
    slug: 'long-cashmere-coat-max-mara-women',
    description: 'A signature Max Mara long cashmere coat known for its luxury and warmth.',
    price: 1190,
    categoryId: '2',
    imageId: 'prod-54',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 30,
    popularity: 99,
    createdAt: '2023-11-03T10:00:00Z',
  },
  {
    id: '55',
    name: 'Short Quilted Jacket – Moncler',
    slug: 'short-quilted-jacket-moncler',
    description: 'A feminine padded jacket offering excellent insulation and iconic Moncler styling.',
    price: 630,
    categoryId: '2',
    imageId: 'prod-55',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 26,
    popularity: 95,
    createdAt: '2023-11-14T10:00:00Z',
  },
  {
    id: '56',
    name: 'Oversized Cable-Knit Sweater – Chloé',
    slug: 'oversized-cable-knit-sweater-chloe',
    description: 'A cozy oversized cable-knit sweater that balances comfort and refined design.',
    price: 350,
    categoryId: '2',
    imageId: 'prod-56',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 19,
    popularity: 87,
    createdAt: '2023-10-30T10:00:00Z',
  },
  {
    id: '57',
    name: 'Wool Pencil Skirt – Hugo Boss',
    slug: 'wool-pencil-skirt-hugo-boss',
    description: 'A refined wool pencil skirt suitable for office wear and winter events.',
    price: 210,
    categoryId: '2',
    imageId: 'prod-57',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 12,
    popularity: 84,
    createdAt: '2023-10-05T10:00:00Z',
  },
  {
    id: '58',
    name: 'Pleated Long Dress – Valentino',
    slug: 'pleated-long-dress-valentino',
    description: 'An elegant pleated long dress embodying timeless Valentino sophistication.',
    price: 1150,
    categoryId: '2',
    imageId: 'prod-58',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M'],
    rating: 5.0,
    reviewCount: 10,
    popularity: 93,
    createdAt: '2023-11-22T10:00:00Z',
  },
  {
    id: '59',
    name: 'Premium Cotton Shirt – Burberry',
    slug: 'premium-cotton-shirt-burberry',
    description: 'A perfectly tailored shirt made from high-quality cotton for everyday elegance.',
    price: 260,
    categoryId: '2',
    imageId: 'prod-59',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 38,
    popularity: 90,
    createdAt: '2023-09-15T10:00:00Z',
  },
  {
    id: '60',
    name: 'Silk Wrap Dress – Diane von Fürstenberg',
    slug: 'silk-wrap-dress-diane-von-furstenberg',
    description: 'An iconic wrap dress crafted in luxurious silk for effortless winter chic.',
    price: 520,
    categoryId: '2',
    imageId: 'prod-60',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 92,
    createdAt: '2023-10-12T10:00:00Z',
  },
  {
    id: '61',
    name: 'Tailored Pants – Dior Women',
    slug: 'tailored-pants-dior-women',
    description: 'High-fashion tailored pants designed to elevate winter looks with precision.',
    price: 680,
    categoryId: '2',
    imageId: 'prod-61',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 14,
    popularity: 94,
    createdAt: '2023-11-25T10:00:00Z',
  },
  {
    id: '62',
    name: 'Boat-Neck Sweater – Ralph Lauren',
    slug: 'boat-neck-sweater-ralph-lauren',
    description: 'A soft knit sweater featuring an elegant boat neckline.',
    price: 240,
    categoryId: '2',
    imageId: 'prod-62',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.7,
    reviewCount: 20,
    popularity: 88,
    createdAt: '2023-11-27T10:00:00Z',
  },
  {
    id: '63',
    name: 'Long Cashmere Cardigan – Brunello Cucinelli',
    slug: 'long-cashmere-cardigan-brunello-cucinelli',
    description: 'A luxurious long cardigan crafted from premium cashmere for unmatched warmth.',
    price: 890,
    categoryId: '2',
    imageId: 'prod-63',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 15,
    popularity: 92,
    createdAt: '2023-11-29T10:00:00Z',
  },
  {
    id: '64',
    name: 'Asymmetric Dress – Givenchy',
    slug: 'asymmetric-dress-givenchy',
    description: 'A couture-style asymmetric dress with modern winter sophistication.',
    price: 980,
    categoryId: '2',
    imageId: 'prod-64',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.8,
    reviewCount: 12,
    popularity: 90,
    createdAt: '2023-12-01T10:00:00Z',
  },
  {
    id: '65',
    name: 'Satin Blouse – Stella McCartney',
    slug: 'satin-blouse-stella-mccartney',
    description: 'A smooth satin blouse offering a minimalist yet refined silhouette.',
    price: 320,
    categoryId: '2',
    imageId: 'prod-65',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.7,
    reviewCount: 18,
    popularity: 86,
    createdAt: '2023-12-03T10:00:00Z',
  },
  {
    id: '66',
    name: 'Pantsuit Jumpsuit – Balenciaga',
    slug: 'pantsuit-jumpsuit-balenciaga',
    description: 'A sculptural and elegant jumpsuit designed to stand out during winter occasions.',
    price: 770,
    categoryId: '2',
    imageId: 'prod-66',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 93,
    createdAt: '2023-12-05T10:00:00Z',
  },
  // Accessories
  {
    id: '67',
    name: 'Stainless Steel Black Chrono Watch – Luxury',
    slug: 'stainless-steel-black-chrono-watch-luxury',
    description: 'A refined black stainless steel chronograph watch combining modern style and precise functionality.',
    price: 520,
    categoryId: '3',
    imageId: 'prod-67',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 30,
    popularity: 92,
    createdAt: '2023-11-01T11:00:00Z',
  },
  {
    id: '68',
    name: 'Sports Silicone Watch – HydroSport 5 ATM',
    slug: 'sports-silicone-watch-hydrosport-5-atm',
    description: 'A durable and waterproof sports watch suitable for active winter lifestyles.',
    price: 150,
    categoryId: '3',
    imageId: 'prod-68',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 45,
    popularity: 88,
    createdAt: '2023-11-02T11:00:00Z',
  },
  {
    id: '69',
    name: 'Classic Brown Leather Watch – Heritage',
    slug: 'classic-brown-leather-watch-heritage',
    description: 'A timeless brown leather watch with premium craftsmanship and versatile style.',
    price: 420,
    categoryId: '3',
    imageId: 'prod-69',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 35,
    popularity: 90,
    createdAt: '2023-11-03T11:00:00Z',
  },
  {
    id: '70',
    name: 'Silver Metal Watch – Blue Vision',
    slug: 'silver-metal-watch-blue-vision',
    description: 'An elegant silver watch with a modern blue dial, perfect for office or formal events.',
    price: 360,
    categoryId: '3',
    imageId: 'prod-70',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 28,
    popularity: 89,
    createdAt: '2023-11-04T11:00:00Z',
  },
  {
    id: '71',
    name: 'Digital LED Urban Watch – Tech Series',
    slug: 'digital-led-urban-watch-tech-series',
    description: 'A contemporary LED watch with multifunction display and sporty aesthetic.',
    price: 140,
    categoryId: '3',
    imageId: 'prod-71',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.6,
    reviewCount: 50,
    popularity: 85,
    createdAt: '2023-11-05T11:00:00Z',
  },
  {
    id: '72',
    name: 'Rose Gold Dial Watch – Executive Elite',
    slug: 'rose-gold-dial-watch-executive-elite',
    description: 'A luxurious rose gold dial watch for sophisticated everyday wear.',
    price: 620,
    categoryId: '3',
    imageId: 'prod-72',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 93,
    createdAt: '2023-11-06T11:00:00Z',
  },
  {
    id: '73',
    name: 'Titanium Steel Chronograph Watch – Pro Series',
    slug: 'titanium-steel-chronograph-watch-pro-series',
    description: 'A high-performance titanium chronograph watch designed for precision and style.',
    price: 580,
    categoryId: '3',
    imageId: 'prod-73',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 91,
    createdAt: '2023-11-07T11:00:00Z',
  },
  {
    id: '74',
    name: 'Knitted Black Wool Beanie – Nordic Luxe',
    slug: 'knitted-black-wool-beanie-nordic-luxe',
    description: 'A cozy black wool beanie featuring elegant Nordic-inspired stitching.',
    price: 120,
    categoryId: '3',
    imageId: 'prod-74',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 40,
    popularity: 88,
    createdAt: '2023-11-08T11:00:00Z',
  },
  {
    id: '75',
    name: 'Thick Grey Winter Beanie – Essential',
    slug: 'thick-grey-winter-beanie-essential',
    description: 'A warm thick grey beanie ideal for cold weather comfort.',
    price: 110,
    categoryId: '3',
    imageId: 'prod-75',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 55,
    popularity: 87,
    createdAt: '2023-11-09T11:00:00Z',
  },
  {
    id: '76',
    name: 'Premium Virgin Wool Scarf – Alpine Soft',
    slug: 'premium-virgin-wool-scarf-alpine-soft',
    description: 'A soft and elegant virgin wool scarf providing superior warmth and style.',
    price: 200,
    categoryId: '3',
    imageId: 'prod-76',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 38,
    popularity: 90,
    createdAt: '2023-11-10T11:00:00Z',
  },
  {
    id: '77',
    name: 'Polar Snood – Winter Shield Premium',
    slug: 'polar-snood-winter-shield-premium',
    description: 'A cozy polar fleece snood offering maximum winter protection.',
    price: 150,
    categoryId: '3',
    imageId: 'prod-77',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 30,
    popularity: 86,
    createdAt: '2023-11-11T11:00:00Z',
  },
  {
    id: '78',
    name: 'Reversible Streetwear Beanie – Urban Knit',
    slug: 'reversible-streetwear-beanie-urban-knit',
    description: 'A stylish reversible beanie suitable for urban winter outfits.',
    price: 110,
    categoryId: '3',
    imageId: 'prod-78',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 42,
    popularity: 84,
    createdAt: '2023-11-12T11:00:00Z',
  },
  {
    id: '79',
    name: 'Thermal Touchscreen Gloves – Tech Gloves',
    slug: 'thermal-touchscreen-gloves-tech-gloves',
    description: 'Insulated gloves allowing touchscreen usage without removing them.',
    price: 130,
    categoryId: '3',
    imageId: 'prod-79',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 33,
    popularity: 89,
    createdAt: '2023-11-13T11:00:00Z',
  },
  {
    id: '80',
    name: 'Slimfold Leather Wallet – Premium',
    slug: 'slimfold-leather-wallet-premium',
    description: 'A sleek leather wallet designed for modern convenience and elegance.',
    price: 220,
    categoryId: '3',
    imageId: 'prod-80',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 28,
    popularity: 91,
    createdAt: '2023-11-14T11:00:00Z',
  },
  {
    id: '81',
    name: 'Leather Shoulder Bag – Executive Bag',
    slug: 'leather-shoulder-bag-executive-bag',
    description: 'A refined leather shoulder bag combining premium material and practicality.',
    price: 320,
    categoryId: '3',
    imageId: 'prod-81',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 25,
    popularity: 90,
    createdAt: '2023-11-15T11:00:00Z',
  },
  {
    id: '82',
    name: 'Elegant Gold Watch – Golden Lady',
    slug: 'elegant-gold-watch-golden-lady',
    description: 'A glamorous gold watch designed for stylish everyday and formal wear.',
    price: 480,
    categoryId: '3',
    imageId: 'prod-82',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 20,
    popularity: 92,
    createdAt: '2023-11-16T11:00:00Z',
  },
  {
    id: '83',
    name: 'Minimalist Silver Watch – Silver Pure',
    slug: 'minimalist-silver-watch-silver-pure',
    description: 'A sleek silver watch with minimalist design for refined winter fashion.',
    price: 450,
    categoryId: '3',
    imageId: 'prod-83',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 18,
    popularity: 89,
    createdAt: '2023-11-17T11:00:00Z',
  },
  {
    id: '84',
    name: 'Beige Leather Watch – Soft Elegance',
    slug: 'beige-leather-watch-soft-elegance',
    description: 'A soft beige leather watch offering understated sophistication.',
    price: 420,
    categoryId: '3',
    imageId: 'prod-84',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 15,
    popularity: 87,
    createdAt: '2023-11-18T11:00:00Z',
  },
  {
    id: '85',
    name: 'Rose Gold Milanese Watch – Rose Queen',
    slug: 'rose-gold-milanese-watch-rose-queen',
    description: 'An elegant rose gold watch with Milanese strap, perfect for chic winter outfits.',
    price: 560,
    categoryId: '3',
    imageId: 'prod-85',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 93,
    createdAt: '2023-11-19T11:00:00Z',
  },
  {
    id: '86',
    name: 'Wool Beanie with Faux Fur Pompom – Cozy Glam',
    slug: 'wool-beanie-with-faux-fur-pompom-cozy-glam',
    description: 'A luxurious winter beanie with faux fur pompom for added glamour.',
    price: 130,
    categoryId: '3',
    imageId: 'prod-86',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 35,
    popularity: 88,
    createdAt: '2023-11-20T11:00:00Z',
  },
  {
    id: '87',
    name: 'Oversized Long Beanie – Urban Chic',
    slug: 'oversized-long-beanie-urban-chic',
    description: 'A cozy oversized beanie that pairs perfectly with casual winter outfits.',
    price: 110,
    categoryId: '3',
    imageId: 'prod-87',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 40,
    popularity: 85,
    createdAt: '2023-11-21T11:00:00Z',
  },
  {
    id: '88',
    name: 'Knitted Pearl Beanie – Winter Pearl',
    slug: 'knitted-pearl-beanie-winter-pearl',
    description: 'A chic knitted beanie embellished with pearl details for elegance.',
    price: 120,
    categoryId: '3',
    imageId: 'prod-88',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 28,
    popularity: 89,
    createdAt: '2023-11-22T11:00:00Z',
  },
  {
    id: '89',
    name: 'Oversized Faux Fur Scarf – Luxe Soft',
    slug: 'oversized-faux-fur-scarf-luxe-soft',
    description: 'An oversized scarf in soft faux fur providing warmth and luxury.',
    price: 200,
    categoryId: '3',
    imageId: 'prod-89',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 91,
    createdAt: '2023-11-23T11:00:00Z',
  },
  {
    id: '90',
    name: 'Cable Knit Plush Scarf – Warm Plush',
    slug: 'cable-knit-plush-scarf-warm-plush',
    description: 'A thick, cable-knit scarf designed for elegant winter styling.',
    price: 150,
    categoryId: '3',
    imageId: 'prod-90',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 30,
    popularity: 88,
    createdAt: '2023-11-24T11:00:00Z',
  },
  {
    id: '91',
    name: 'Elegant Pattern Winter Shawl – Elegant Wrap',
    slug: 'elegant-pattern-winter-shawl-elegant-wrap',
    description: 'A patterned winter shawl combining sophistication and warmth.',
    price: 180,
    categoryId: '3',
    imageId: 'prod-91',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 22,
    popularity: 86,
    createdAt: '2023-11-25T11:00:00Z',
  },
  {
    id: '92',
    name: 'Printed Cashmere Scarf – Cashmere Touch',
    slug: 'printed-cashmere-scarf-cashmere-touch',
    description: 'A luxurious printed cashmere scarf designed for premium winter fashion.',
    price: 220,
    categoryId: '3',
    imageId: 'prod-92',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 18,
    popularity: 90,
    createdAt: '2023-11-26T11:00:00Z',
  },
  {
    id: '93',
    name: 'Leather Polar Gloves – Lady Warm',
    slug: 'leather-polar-gloves-lady-warm',
    description: 'Elegant double-layered leather gloves lined with polar fleece for winter warmth.',
    price: 140,
    categoryId: '3',
    imageId: 'prod-93',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 20,
    popularity: 88,
    createdAt: '2023-11-27T11:00:00Z',
  },
  {
    id: '94',
    name: 'Mini Chic Handbag – Mini Glam',
    slug: 'mini-chic-handbag-mini-glam',
    description: 'A stylish compact handbag perfect for evening outings and winter events.',
    price: 180,
    categoryId: '3',
    imageId: 'prod-94',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 15,
    popularity: 87,
    createdAt: '2023-11-28T11:00:00Z',
  },
  {
    id: '95',
    name: 'Silver Pendant Earrings – Shine Drop',
    slug: 'silver-pendant-earrings-shine-drop',
    description: 'Elegant silver drop earrings adding sparkle to winter outfits.',
    price: 120,
    categoryId: '3',
    imageId: 'prod-95',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 25,
    popularity: 89,
    createdAt: '2023-11-29T11:00:00Z',
  },
  {
    id: '96',
    name: 'Evening Clutch – Shine Night Premium',
    slug: 'evening-clutch-shine-night-premium',
    description: 'A luxurious evening clutch designed for premium winter events.',
    price: 150,
    categoryId: '3',
    imageId: 'prod-96',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 20,
    popularity: 91,
    createdAt: '2023-11-30T11:00:00Z',
  },
  // Winter Collection
  {
    id: '1',
    name: 'Long Wool Coat – Hugo Boss',
    slug: 'long-wool-coat-hugo-boss-winter',
    description: 'A sophisticated long wool coat crafted from fine merino wool. Provides excellent insulation, a structured silhouette, and a timeless luxury style suitable for formal winter outfits.',
    price: 420,
    categoryId: '4',
    imageId: 'prod-1',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 15,
    popularity: 92,
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Quilted Down Jacket – Moncler',
    slug: 'quilted-down-jacket-moncler-winter',
    description: 'A premium quilted down jacket with ultra-light insulation. Warm, water-resistant, and extremely comfortable—an iconic Moncler piece for cold winter days.',
    price: 680,
    categoryId: '4',
    imageId: 'prod-2',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 98,
    createdAt: '2023-11-05T10:00:00Z',
  },
  {
    id: '3',
    name: 'Arctic Parka – Canada Goose',
    slug: 'arctic-parka-canada-goose-winter',
    description: 'An extremely warm Arctic parka designed to withstand harsh temperatures. Windproof, breathable, and highly durable—a top-tier winter choice.',
    price: 890,
    categoryId: '4',
    imageId: 'prod-3',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 5.0,
    reviewCount: 42,
    popularity: 99,
    createdAt: '2023-10-28T10:00:00Z',
  },
  {
    id: '4',
    name: 'Cashmere Coat – Loro Piana (Men)',
    slug: 'cashmere-coat-loro-piana-men-winter',
    description: 'A luxurious coat made from pure cashmere, offering a soft touch and exceptional craftsmanship. A refined Italian design for elegant winter style.',
    price: 1250,
    categoryId: '4',
    imageId: 'prod-4',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L'],
    rating: 5.0,
    reviewCount: 18,
    popularity: 95,
    createdAt: '2023-11-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Shearling Jacket – Saint Laurent',
    slug: 'shearling-jacket-saint-laurent-winter',
    description: 'A premium lambskin jacket with shearling lining for maximum warmth. Stylish, bold, and perfect for luxury winter outfits.',
    price: 1480,
    categoryId: '4',
    imageId: 'prod-5',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 93,
    createdAt: '2023-11-12T10:00:00Z',
  },
  {
    id: '6',
    name: 'Merino Wool Turtleneck – Paul Smith',
    slug: 'merino-wool-turtleneck-paul-smith-winter',
    description: 'A soft and breathable turtleneck sweater made from 100% merino wool. Ideal for layering and polished winter looks.',
    price: 210,
    categoryId: '4',
    imageId: 'prod-6',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 35,
    popularity: 88,
    createdAt: '2023-10-15T10:00:00Z',
  },
  {
    id: '7',
    name: 'Lined Overshirt – Acne Studios (Men)',
    slug: 'lined-overshirt-acne-studios-men-winter',
    description: 'A warm lined overshirt with a minimalist Scandinavian design. Versatile, comfortable, and perfect for cold days.',
    price: 270,
    categoryId: '4',
    imageId: 'prod-7',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 28,
    popularity: 85,
    createdAt: '2023-10-20T10:00:00Z',
  },
  {
    id: '8',
    name: 'Down Vest – Polo Ralph Lauren',
    slug: 'down-vest-polo-ralph-lauren-winter',
    description: 'A lightweight sleeveless down vest with a sporty fit. Ideal for transitional weather and outdoor activities.',
    price: 190,
    categoryId: '4',
    imageId: 'prod-8',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 40,
    popularity: 90,
    createdAt: '2023-09-25T10:00:00Z',
  },
  {
    id: '9',
    name: 'Double-Breasted Trench Coat – Burberry',
    slug: 'double-breasted-trench-coat-burberry-winter',
    description: 'A classic double-breasted trench coat crafted from water-resistant fabric. A timeless British luxury icon.',
    price: 1090,
    categoryId: '4',
    imageId: 'prod-9',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 55,
    popularity: 96,
    createdAt: '2023-09-10T10:00:00Z',
  },
  {
    id: '10',
    name: 'Thick Cable-Knit Sweater – Dior Homme',
    slug: 'thick-cable-knit-sweater-dior-homme-winter',
    description: 'A premium cable-knit sweater made from thick wool yarn. Warm, elegant, and ideal for sophisticated winter outfits.',
    price: 450,
    categoryId: '4',
    imageId: 'prod-10',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 30,
    popularity: 91,
    createdAt: '2023-10-18T10:00:00Z',
  },
  {
    id: '11',
    name: 'Technical Waterproof Jacket – TNF Black Series',
    slug: 'technical-waterproof-jacket-tnf-black-series-winter',
    description: 'A high-performance waterproof jacket from The North Face Black Series. Breathable, durable, and designed for urban and outdoor winter conditions.',
    price: 320,
    categoryId: '4',
    imageId: 'prod-11',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 45,
    popularity: 89,
    createdAt: '2023-11-15T10:00:00Z',
  },

  // Winter Items for Women
  {
    id: '12',
    name: 'Silk Midi Dress – Gucci',
    slug: 'silk-midi-dress-gucci-winter',
    description: 'A refined silk midi dress with a smooth, fluid drape. Luxurious and perfect for winter celebrations.',
    price: 950,
    categoryId: '4',
    imageId: 'prod-12',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 28,
    popularity: 94,
    createdAt: '2023-11-08T10:00:00Z',
  },
  {
    id: '13',
    name: 'Double-Breasted Blazer – Balmain',
    slug: 'double-breasted-blazer-balmain-winter',
    description: 'A signature Balmain blazer featuring gold-tone buttons and a tailored silhouette. Powerful, elegant, and iconic.',
    price: 1350,
    categoryId: '4',
    imageId: 'prod-13',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 35,
    popularity: 97,
    createdAt: '2023-11-02T10:00:00Z',
  },
  {
    id: '14',
    name: 'Cashmere Turtleneck – Loro Piana (Women)',
    slug: 'cashmere-turtleneck-loro-piana-women-winter',
    description: 'A premium turtleneck crafted from pure cashmere. Soft, warm, and timelessly stylish.',
    price: 620,
    categoryId: '4',
    imageId: 'prod-14',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 20,
    popularity: 96,
    createdAt: '2023-10-25T10:00:00Z',
  },
  {
    id: '15',
    name: 'Wide Wool Trousers – Max Mara',
    slug: 'wide-wool-trousers-max-mara-winter',
    description: 'Elegant wide-leg trousers made from fine wool. Perfect for business or refined city looks.',
    price: 340,
    categoryId: '4',
    imageId: 'prod-15',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 15,
    popularity: 88,
    createdAt: '2023-10-10T10:00:00Z',
  },
  {
    id: '16',
    name: 'Premium Slim Jeans – Diesel',
    slug: 'premium-slim-jeans-diesel-winter',
    description: 'A high-quality slim-fit jeans offering comfort and a modern silhouette.',
    price: 180,
    categoryId: '4',
    imageId: 'prod-16',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['26', '27', '28', '29', '30'],
    rating: 4.6,
    reviewCount: 50,
    popularity: 85,
    createdAt: '2023-09-20T10:00:00Z',
  },
  {
    id: '17',
    name: 'Printed Silk Blouse – Saint Laurent',
    slug: 'printed-silk-blouse-saint-laurent-winter',
    description: 'A luxurious printed silk blouse with artistic detailing. Feminine, elegant, and versatile.',
    price: 430,
    categoryId: '4',
    imageId: 'prod-17',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 91,
    createdAt: '2023-11-18T10:00:00Z',
  },
  {
    id: '18',
    name: 'Wool Mini Dress – Prada',
    slug: 'wool-mini-dress-prada-winter',
    description: 'A refined wool mini dress with clean lines and premium craftsmanship.',
    price: 720,
    categoryId: '4',
    imageId: 'prod-18',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.8,
    reviewCount: 18,
    popularity: 89,
    createdAt: '2023-11-20T10:00:00Z',
  },
  {
    id: '19',
    name: 'Long Cashmere Coat – Max Mara',
    slug: 'long-cashmere-coat-max-mara-winter',
    description: 'An iconic Max Mara coat made from pure cashmere—luxurious, warm, and timeless.',
    price: 1290,
    categoryId: '4',
    imageId: 'prod-19',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 30,
    popularity: 99,
    createdAt: '2023-11-03T10:00:00Z',
  },
  {
    id: '20',
    name: 'Quilted Short Jacket – Moncler',
    slug: 'quilted-short-jacket-moncler-winter',
    description: 'A stylish short down jacket with premium insulation and a sleek winter design.',
    price: 620,
    categoryId: '4',
    imageId: 'prod-20',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 26,
    popularity: 95,
    createdAt: '2023-11-14T10:00:00Z',
  },
  {
    id: '21',
    name: 'Oversized Cable-Knit Sweater – Chloé',
    slug: 'oversized-cable-knit-sweater-chloe-winter',
    description: 'A cozy oversized sweater with cable-knit detailing. Warm, relaxed, and elegant.',
    price: 350,
    categoryId: '4',
    imageId: 'prod-21',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 19,
    popularity: 87,
    createdAt: '2023-10-30T10:00:00Z',
  },
  {
    id: '22',
    name: 'Wool Pencil Skirt – Hugo Boss',
    slug: 'wool-pencil-skirt-hugo-boss-winter',
    description: 'A refined wool pencil skirt suitable for office wear and winter events.',
    price: 210,
    categoryId: '4',
    imageId: 'prod-22',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 12,
    popularity: 84,
    createdAt: '2023-10-05T10:00:00Z',
  },
  {
    id: '23',
    name: 'Pleated Evening Gown – Valentino',
    slug: 'pleated-evening-gown-valentino-winter',
    description: 'A luxurious pleated evening dress with elegant movement and premium finishing.',
    price: 1650,
    categoryId: '4',
    imageId: 'prod-23',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M'],
    rating: 5.0,
    reviewCount: 10,
    popularity: 93,
    createdAt: '2023-11-22T10:00:00Z',
  },
  {
    id: '24',
    name: 'Premium Cotton Shirt – Burberry',
    slug: 'premium-cotton-shirt-burberry-winter',
    description: 'A high-end cotton shirt with a polished and timeless look.',
    price: 240,
    categoryId: '4',
    imageId: 'prod-24',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 38,
    popularity: 90,
    createdAt: '2023-09-15T10:00:00Z',
  },
  {
    id: '25',
    name: 'Silk Wrap Dress – Diane von Fürstenberg',
    slug: 'silk-wrap-dress-diane-von-furstenberg-winter',
    description: 'A signature wrap dress crafted from pure silk—feminine, flattering, and iconic.',
    price: 580,
    categoryId: '4',
    imageId: 'prod-25',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 92,
    createdAt: '2023-10-12T10:00:00Z',
  },
  {
    id: '26',
    name: 'Tailored Wool Trousers – Dior (Women)',
    slug: 'tailored-wool-trousers-dior-women-winter',
    description: 'Elegant tailored wool trousers offering a sleek and sophisticated silhouette.',
    price: 780,
    categoryId: '4',
    imageId: 'prod-26',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 14,
    popularity: 94,
    createdAt: '2023-11-25T10:00:00Z',
  },
];


export const reviews: Review[] = [
    { id: '1', author: 'Alex Johnson', authorImageId: 'avatar-1', rating: 5, text: 'Absolutely love this! The quality is outstanding, and it fits perfectly. Will definitely be buying more from this brand.', date: '2 weeks ago'},
    { id: '2', author: 'Samantha Miller', authorImageId: 'avatar-2', rating: 5, text: 'Exceeded my expectations. The material feels so luxurious. Fast shipping and beautiful packaging too!', date: '3 weeks ago'},
    { id: '3', author: 'Ben Carter', authorImageId: 'avatar-3', rating: 4, text: 'Great product overall. The color is slightly different than pictured but still very nice. Sizing is true to fit.', date: '1 month ago'},
    { id: '4', author: 'Jessica Chen', authorImageId: 'avatar-4', rating: 5, text: 'A new wardrobe staple for me. It\'s versatile and incredibly well-made. I\'ve received so many compliments.', date: '1 month ago'},
    { id: '5', author: 'Michael Brown', authorImageId: 'avatar-5', rating: 4, text: 'Very happy with my purchase. Good value for the price. Would recommend to a friend.', date: '2 months ago'},
];


    