import type { Category, Product, Review } from './types';

export const categories: Category[] = [
  { id: '1', name: "Men's Clothing", slug: 'mens-clothing', imageId: 'cat-mens' },
  { id: '2', name: "Women's Clothing", slug: 'womens-clothing', imageId: 'cat-womens' },
  { id: '3', name: 'Accessories', slug: 'accessories', imageId: 'cat-accessories' },
  { id: '4', name: 'Winter Collection', slug: 'winter-collection', imageId: 'cat-winter' },
];

export const products: Product[] = [
  // Men's Clothing
  {
    id: '1',
    name: 'Modern Fit Tee',
    slug: 'modern-fit-tee',
    description: 'A classic tee with a modern twist. Made from 100% premium cotton for ultimate comfort and durability. Perfect for any casual occasion.',
    price: 49.99,
    categoryId: '1',
    imageId: 'prod-1',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 120,
    popularity: 95,
    createdAt: '2023-10-01T12:00:00Z',
  },
  {
    id: '2',
    name: 'Slim-Fit Chinos',
    slug: 'slim-fit-chinos',
    description: 'Versatile slim-fit chinos that can be dressed up or down. Crafted with a slight stretch for all-day comfort and a perfect fit.',
    price: 89.99,
    categoryId: '1',
    imageId: 'prod-2',
    galleryImageIds: ['prod-2', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['30x30', '32x32', '34x32', '36x34'],
    rating: 4.7,
    reviewCount: 95,
    popularity: 90,
    createdAt: '2023-09-15T12:00:00Z',
  },
  {
    id: '3',
    name: 'Leather Derby Shoes',
    slug: 'leather-derby-shoes',
    description: 'Timeless derby shoes made from genuine leather. A staple for any gentleman\'s wardrobe, featuring a durable sole and comfortable insole.',
    price: 149.99,
    categoryId: '1',
    imageId: 'prod-3',
    galleryImageIds: ['prod-3', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['8', '9', '10', '11', '12'],
    rating: 4.8,
    reviewCount: 210,
    popularity: 85,
    createdAt: '2023-11-01T12:00:00Z',
  },
  // Women's Clothing
  {
    id: '4',
    name: 'Elegant Midi Dress',
    slug: 'elegant-midi-dress',
    description: 'A stunning midi dress perfect for special occasions. Features a flattering silhouette and is made from a luxurious, flowing fabric.',
    price: 129.99,
    categoryId: '2',
    imageId: 'prod-4',
    galleryImageIds: ['prod-4', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 150,
    popularity: 98,
    createdAt: '2023-10-20T12:00:00Z',
  },
  {
    id: '5',
    name: 'Silk-Blend Blouse',
    slug: 'silk-blend-blouse',
    description: 'A luxurious silk-blend blouse that feels amazing on the skin. Its versatile design makes it suitable for both office and evening wear.',
    price: 79.99,
    categoryId: '2',
    imageId: 'prod-5',
    galleryImageIds: ['prod-5', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 88,
    popularity: 88,
    createdAt: '2023-08-01T12:00:00Z',
  },
  {
    id: '6',
    name: 'High-Waisted Skirt',
    slug: 'high-waisted-skirt',
    description: 'A chic high-waisted skirt that accentuates your figure. Pairs perfectly with our silk-blend blouse or a simple tee.',
    price: 69.99,
    categoryId: '2',
    imageId: 'prod-6',
    galleryImageIds: ['prod-6', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.5,
    reviewCount: 75,
    popularity: 82,
    createdAt: '2023-11-05T12:00:00Z',
  },
  // Accessories
  {
    id: '7',
    name: 'Classic Leather Watch',
    slug: 'classic-leather-watch',
    description: 'An elegant timepiece with a genuine leather strap and stainless steel case. Minimalist design meets Swiss precision.',
    price: 249.99,
    categoryId: '3',
    imageId: 'prod-7',
    galleryImageIds: ['prod-7', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 300,
    popularity: 99,
    createdAt: '2023-07-10T12:00:00Z',
  },
  {
    id: '8',
    name: 'Aviator Sunglasses',
    slug: 'aviator-sunglasses',
    description: 'Iconic aviator sunglasses with polarized lenses for 100% UV protection. Lightweight frame for maximum comfort.',
    price: 99.99,
    categoryId: '3',
    imageId: 'prod-8',
    galleryImageIds: ['prod-8', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 180,
    popularity: 92,
    createdAt: '2023-06-01T12:00:00Z',
  },
  {
    id: '9',
    name: 'Italian Leather Bag',
    slug: 'italian-leather-bag',
    description: 'A beautifully crafted handbag made from the finest Italian leather. Spacious and stylish, it\'s the perfect accessory for any outfit.',
    price: 349.99,
    categoryId: '3',
    imageId: 'prod-9',
    galleryImageIds: ['prod-9', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 130,
    popularity: 89,
    createdAt: '2023-09-01T12:00:00Z',
  },
  // Winter Collection
  {
    id: '10',
    name: 'Arctic Parka',
    slug: 'arctic-parka',
    description: 'Stay warm in the harshest conditions with our Arctic Parka. Features a waterproof shell, down insulation, and a faux-fur hood.',
    price: 499.99,
    categoryId: '4',
    imageId: 'prod-10',
    galleryImageIds: ['prod-10', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.9,
    reviewCount: 250,
    popularity: 96,
    createdAt: '2023-11-10T12:00:00Z',
  },
  {
    id: '11',
    name: 'Cashmere Wool Scarf',
    slug: 'cashmere-wool-scarf',
    description: 'A luxuriously soft scarf made from a blend of cashmere and merino wool. The perfect accessory to keep you warm and stylish.',
    price: 89.99,
    categoryId: '4',
    imageId: 'prod-11',
    galleryImageIds: ['prod-11', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.8,
    reviewCount: 110,
    popularity: 85,
    createdAt: '2023-10-25T12:00:00Z',
  },
  {
    id: '12',
    name: 'Merino Wool Beanie',
    slug: 'merino-wool-beanie',
    description: 'A classic beanie knitted from 100% merino wool. Breathable, warm, and incredibly soft for all-day comfort.',
    price: 39.99,
    categoryId: '4',
    imageId: 'prod-12',
    galleryImageIds: ['prod-12', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 150,
    popularity: 87,
    createdAt: '2023-11-15T12:00:00Z',
  },
];

export const reviews: Review[] = [
    { id: '1', author: 'Alex Johnson', authorImageId: 'avatar-1', rating: 5, text: 'Absolutely love this! The quality is outstanding, and it fits perfectly. Will definitely be buying more from this brand.', date: '2 weeks ago'},
    { id: '2', author: 'Samantha Miller', authorImageId: 'avatar-2', rating: 5, text: 'Exceeded my expectations. The material feels so luxurious. Fast shipping and beautiful packaging too!', date: '3 weeks ago'},
    { id: '3', author: 'Ben Carter', authorImageId: 'avatar-3', rating: 4, text: 'Great product overall. The color is slightly different than pictured but still very nice. Sizing is true to fit.', date: '1 month ago'},
    { id: '4', author: 'Jessica Chen', authorImageId: 'avatar-4', rating: 5, text: 'A new wardrobe staple for me. It\'s versatile and incredibly well-made. I\'ve received so many compliments.', date: '1 month ago'},
    { id: '5', author: 'Michael Brown', authorImageId: 'avatar-5', rating: 4, text: 'Very happy with my purchase. Good value for the price. Would recommend to a friend.', date: '2 months ago'},
];
