import type { Category, Product, Review } from './types';

export const categories: Category[] = [
  { id: '1', name: "Men's Clothing", slug: 'mens-clothing', imageId: 'cat-mens' },
  { id: '2', name: "Women's Clothing", slug: 'womens-clothing', imageId: 'cat-womens' },
  { id: '3', name: 'Accessories', slug: 'accessories', imageId: 'cat-accessories' },
  { id: '4', name: 'Winter Collection', slug: 'winter-collection', imageId: 'cat-winter' },
];

export const products: Product[] = [
  // Winter Items for Men
  {
    id: '1',
    name: 'Long Wool Coat – Hugo Boss',
    slug: 'long-wool-coat-hugo-boss',
    description: 'A sophisticated long wool coat crafted from fine merino wool. Provides excellent insulation, a structured silhouette, and a timeless luxury style suitable for formal winter outfits.',
    price: 420,
    categoryId: '4',
    imageId: 'prod-1',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 15,
    popularity: 92,
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Quilted Down Jacket – Moncler',
    slug: 'quilted-down-jacket-moncler',
    description: 'A premium quilted down jacket with ultra-light insulation. Warm, water-resistant, and extremely comfortable—an iconic Moncler piece for cold winter days.',
    price: 680,
    categoryId: '4',
    imageId: 'prod-2',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 98,
    createdAt: '2023-11-05T10:00:00Z',
  },
  {
    id: '3',
    name: 'Arctic Parka – Canada Goose',
    slug: 'arctic-parka-canada-goose',
    description: 'An extremely warm Arctic parka designed to withstand harsh temperatures. Windproof, breathable, and highly durable—a top-tier winter choice.',
    price: 890,
    categoryId: '4',
    imageId: 'prod-3',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 5.0,
    reviewCount: 42,
    popularity: 99,
    createdAt: '2023-10-28T10:00:00Z',
  },
  {
    id: '4',
    name: 'Cashmere Coat – Loro Piana (Men)',
    slug: 'cashmere-coat-loro-piana-men',
    description: 'A luxurious coat made from pure cashmere, offering a soft touch and exceptional craftsmanship. A refined Italian design for elegant winter style.',
    price: 1250,
    categoryId: '4',
    imageId: 'prod-4',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L'],
    rating: 5.0,
    reviewCount: 18,
    popularity: 95,
    createdAt: '2023-11-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Shearling Jacket – Saint Laurent',
    slug: 'shearling-jacket-saint-laurent',
    description: 'A premium lambskin jacket with shearling lining for maximum warmth. Stylish, bold, and perfect for luxury winter outfits.',
    price: 1480,
    categoryId: '4',
    imageId: 'prod-5',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 93,
    createdAt: '2023-11-12T10:00:00Z',
  },
  {
    id: '6',
    name: 'Merino Wool Turtleneck – Paul Smith',
    slug: 'merino-wool-turtleneck-paul-smith',
    description: 'A soft and breathable turtleneck sweater made from 100% merino wool. Ideal for layering and polished winter looks.',
    price: 210,
    categoryId: '4',
    imageId: 'prod-6',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 35,
    popularity: 88,
    createdAt: '2023-10-15T10:00:00Z',
  },
  {
    id: '7',
    name: 'Lined Overshirt – Acne Studios (Men)',
    slug: 'lined-overshirt-acne-studios-men',
    description: 'A warm lined overshirt with a minimalist Scandinavian design. Versatile, comfortable, and perfect for cold days.',
    price: 270,
    categoryId: '4',
    imageId: 'prod-7',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 28,
    popularity: 85,
    createdAt: '2023-10-20T10:00:00Z',
  },
  {
    id: '8',
    name: 'Down Vest – Polo Ralph Lauren',
    slug: 'down-vest-polo-ralph-lauren',
    description: 'A lightweight sleeveless down vest with a sporty fit. Ideal for transitional weather and outdoor activities.',
    price: 190,
    categoryId: '4',
    imageId: 'prod-8',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 40,
    popularity: 90,
    createdAt: '2023-09-25T10:00:00Z',
  },
  {
    id: '9',
    name: 'Double-Breasted Trench Coat – Burberry',
    slug: 'double-breasted-trench-coat-burberry',
    description: 'A classic double-breasted trench coat crafted from water-resistant fabric. A timeless British luxury icon.',
    price: 1090,
    categoryId: '4',
    imageId: 'prod-9',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 4.9,
    reviewCount: 55,
    popularity: 96,
    createdAt: '2023-09-10T10:00:00Z',
  },
  {
    id: '10',
    name: 'Thick Cable-Knit Sweater – Dior Homme',
    slug: 'thick-cable-knit-sweater-dior-homme',
    description: 'A premium cable-knit sweater made from thick wool yarn. Warm, elegant, and ideal for sophisticated winter outfits.',
    price: 450,
    categoryId: '4',
    imageId: 'prod-10',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviewCount: 30,
    popularity: 91,
    createdAt: '2023-10-18T10:00:00Z',
  },
  {
    id: '11',
    name: 'Technical Waterproof Jacket – TNF Black Series',
    slug: 'technical-waterproof-jacket-tnf-black-series',
    description: 'A high-performance waterproof jacket from The North Face Black Series. Breathable, durable, and designed for urban and outdoor winter conditions.',
    price: 320,
    categoryId: '4',
    imageId: 'prod-11',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 45,
    popularity: 89,
    createdAt: '2023-11-15T10:00:00Z',
  },

  // Winter Items for Women
  {
    id: '12',
    name: 'Silk Midi Dress – Gucci',
    slug: 'silk-midi-dress-gucci',
    description: 'A refined silk midi dress with a smooth, fluid drape. Luxurious and perfect for winter celebrations.',
    price: 950,
    categoryId: '4',
    imageId: 'prod-12',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 28,
    popularity: 94,
    createdAt: '2023-11-08T10:00:00Z',
  },
  {
    id: '13',
    name: 'Double-Breasted Blazer – Balmain',
    slug: 'double-breasted-blazer-balmain',
    description: 'A signature Balmain blazer featuring gold-tone buttons and a tailored silhouette. Powerful, elegant, and iconic.',
    price: 1350,
    categoryId: '4',
    imageId: 'prod-1',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 35,
    popularity: 97,
    createdAt: '2023-11-02T10:00:00Z',
  },
  {
    id: '14',
    name: 'Cashmere Turtleneck – Loro Piana (Women)',
    slug: 'cashmere-turtleneck-loro-piana-women',
    description: 'A premium turtleneck crafted from pure cashmere. Soft, warm, and timelessly stylish.',
    price: 620,
    categoryId: '4',
    imageId: 'prod-2',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 20,
    popularity: 96,
    createdAt: '2023-10-25T10:00:00Z',
  },
  {
    id: '15',
    name: 'Wide Wool Trousers – Max Mara',
    slug: 'wide-wool-trousers-max-mara',
    description: 'Elegant wide-leg trousers made from fine wool. Perfect for business or refined city looks.',
    price: 340,
    categoryId: '4',
    imageId: 'prod-3',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 15,
    popularity: 88,
    createdAt: '2023-10-10T10:00:00Z',
  },
  {
    id: '16',
    name: 'Premium Slim Jeans – Diesel',
    slug: 'premium-slim-jeans-diesel',
    description: 'A high-quality slim-fit jeans offering comfort and a modern silhouette.',
    price: 180,
    categoryId: '4',
    imageId: 'prod-4',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['26', '27', '28', '29', '30'],
    rating: 4.6,
    reviewCount: 50,
    popularity: 85,
    createdAt: '2023-09-20T10:00:00Z',
  },
  {
    id: '17',
    name: 'Printed Silk Blouse – Saint Laurent',
    slug: 'printed-silk-blouse-saint-laurent',
    description: 'A luxurious printed silk blouse with artistic detailing. Feminine, elegant, and versatile.',
    price: 430,
    categoryId: '4',
    imageId: 'prod-5',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 22,
    popularity: 91,
    createdAt: '2023-11-18T10:00:00Z',
  },
  {
    id: '18',
    name: 'Wool Mini Dress – Prada',
    slug: 'wool-mini-dress-prada',
    description: 'A refined wool mini dress with clean lines and premium craftsmanship.',
    price: 720,
    categoryId: '4',
    imageId: 'prod-6',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.8,
    reviewCount: 18,
    popularity: 89,
    createdAt: '2023-11-20T10:00:00Z',
  },
  {
    id: '19',
    name: 'Long Cashmere Coat – Max Mara',
    slug: 'long-cashmere-coat-max-mara',
    description: 'An iconic Max Mara coat made from pure cashmere—luxurious, warm, and timeless.',
    price: 1290,
    categoryId: '4',
    imageId: 'prod-7',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 30,
    popularity: 99,
    createdAt: '2023-11-03T10:00:00Z',
  },
  {
    id: '20',
    name: 'Quilted Short Jacket – Moncler',
    slug: 'quilted-short-jacket-moncler',
    description: 'A stylish short down jacket with premium insulation and a sleek winter design.',
    price: 620,
    categoryId: '4',
    imageId: 'prod-8',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 26,
    popularity: 95,
    createdAt: '2023-11-14T10:00:00Z',
  },
  {
    id: '21',
    name: 'Oversized Cable-Knit Sweater – Chloé',
    slug: 'oversized-cable-knit-sweater-chloe',
    description: 'A cozy oversized sweater with cable-knit detailing. Warm, relaxed, and elegant.',
    price: 350,
    categoryId: '4',
    imageId: 'prod-9',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['One Size'],
    rating: 4.7,
    reviewCount: 19,
    popularity: 87,
    createdAt: '2023-10-30T10:00:00Z',
  },
  {
    id: '22',
    name: 'Wool Pencil Skirt – Hugo Boss',
    slug: 'wool-pencil-skirt-hugo-boss',
    description: 'A refined wool pencil skirt suitable for office wear and winter events.',
    price: 210,
    categoryId: '4',
    imageId: 'prod-10',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 12,
    popularity: 84,
    createdAt: '2023-10-05T10:00:00Z',
  },
  {
    id: '23',
    name: 'Pleated Evening Gown – Valentino',
    slug: 'pleated-evening-gown-valentino',
    description: 'A luxurious pleated evening dress with elegant movement and premium finishing.',
    price: 1650,
    categoryId: '4',
    imageId: 'prod-11',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['S', 'M'],
    rating: 5.0,
    reviewCount: 10,
    popularity: 93,
    createdAt: '2023-11-22T10:00:00Z',
  },
  {
    id: '24',
    name: 'Premium Cotton Shirt – Burberry',
    slug: 'premium-cotton-shirt-burberry',
    description: 'A high-end cotton shirt with a polished and timeless look.',
    price: 240,
    categoryId: '4',
    imageId: 'prod-12',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.8,
    reviewCount: 38,
    popularity: 90,
    createdAt: '2023-09-15T10:00:00Z',
  },
  {
    id: '25',
    name: 'Silk Wrap Dress – Diane von Fürstenberg',
    slug: 'silk-wrap-dress-diane-von-furstenberg',
    description: 'A signature wrap dress crafted from pure silk—feminine, flattering, and iconic.',
    price: 580,
    categoryId: '4',
    imageId: 'prod-1',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M'],
    rating: 4.9,
    reviewCount: 25,
    popularity: 92,
    createdAt: '2023-10-12T10:00:00Z',
  },
  {
    id: '26',
    name: 'Tailored Wool Trousers – Dior (Women)',
    slug: 'tailored-wool-trousers-dior-women',
    description: 'Elegant tailored wool trousers offering a sleek and sophisticated silhouette.',
    price: 780,
    categoryId: '4',
    imageId: 'prod-2',
    galleryImageIds: ['prod-gallery-1-1', 'prod-gallery-1-2', 'prod-gallery-1-3'],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    reviewCount: 14,
    popularity: 94,
    createdAt: '2023-11-25T10:00:00Z',
  },
];


export const reviews: Review[] = [
    { id: '1', author: 'Alex Johnson', authorImageId: 'avatar-1', rating: 5, text: 'Absolutely love this! The quality is outstanding, and it fits perfectly. Will definitely be buying more from this brand.', date: '2 weeks ago'},
    { id: '2', author: 'Samantha Miller', authorImageId: 'avatar-2', rating: 5, text: 'Exceeded my expectations. The material feels so luxurious. Fast shipping and beautiful packaging too!', date: '3 weeks ago'},
    { id: '3', author: 'Ben Carter', authorImageId: 'avatar-3', rating: 4, text: 'Great product overall. The color is slightly different than pictured but still very nice. Sizing is true to fit.', date: '1 month ago'},
    { id: '4', author: 'Jessica Chen', authorImageId: 'avatar-4', rating: 5, text: 'A new wardrobe staple for me. It\'s versatile and incredibly well-made. I\'ve received so many compliments.', date: '1 month ago'},
    { id: '5', author: 'Michael Brown', authorImageId: 'avatar-5', rating: 4, text: 'Very happy with my purchase. Good value for the price. Would recommend to a friend.', date: '2 months ago'},
];
